### ISSUE TITLE
Show which renderer to click next

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#110]

**Comment by danaack** [comment]
- Source and target text should be moved a little bit up and right

- Border around the window to click in

- Border should be same colour as the text in keeping with the colour scheme

- No border once the alignment is displayed

**Comment by zifangah** [comment]
@danaack 
- couldnt find anything to add border actor into the renderer, besides textActor, however have trouble with removing/hiding the textActor to make them dispear once it's been clicked on, so for now the best method i can come up is to change the background colour to the colour scheme for now, the change alternates for the two windows

**Comment by danaack** [comment]
@zifangah Another option would be adjusting the background to draw the outer one first (i.e., the border of a different colour) and then set another smaller background of normal colour on top, and reset the backgrounds each time.

**Comment by danaack** [comment]
When VTK first displays, have the source box be green so that the user knows that is the object to click first.

**Comment by danaack** [comment]
Closed #138
