### ISSUE TITLE
Fitted models are sinking into each other

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#114]
Number of iterations? Have less?
Maybe have less surface be counted
Is there a way to "harden" models so that they don't sink?

**Comment by danaack** [comment]
If iterating less times improves this, then check if models are 'fitting' or 'matching' and set number or iterations appropriately.

**Comment by danaack** [comment]
Can be closed #129 ?

**Comment by emersonk** [comment]
No don't close yet. Still looking to prevent overlap.

**Comment by emersonk** [comment]
I am closing this one as Perfit will be taking care of it
