### ISSUE TITLE
Alignment in progress text

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#123]
Needs to be re added in

Also with the new button to switch the heatmap model we need text in the 4th pane to say which model is being shown

**Comment by danaack** [comment]
Alignment box:

- (1) "Alignment in progress"

- (2) "Alignment complete"

Heatmap box:

- (1) "Heatmap calculation in progress"

- (2) "Source file heatmap"

- (3) When "s" key is pressed: "Target file heatmap"

- Alternate between displaying "Source file heatmap" and "Target file heatmap" whenever "s" key is pressed

**Comment by danaack** [comment]
- Change when the "Heatmap calculation in progress" is displayed. It does not show up currently.

- Do not show "Alignment complete" when "Alignment in progress" re-displays when you click enter again after the initial alignment

**Comment by zifangah** [comment]
@kseaman I made a merge after you approved a request, pls check UI-fix again, thanks!
