### ISSUE TITLE
Three clickable points on the stl file

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#13]
-Outputs or saves the coordinates of each point clicked
-Marks each point that has been clicked

**Comment by danaack** [comment]
I'm assuming the loading and viewing of both datasets needs to be complete before this step and then we'll branch off of that to work on this task?

**Comment by danaack** [comment]
- [ ] Outputs and saves the coordinates of each point clicked

- [ ] Marks each point that has been clicked

- Alternates between reference and production panes (i.e., select point 1 on reference pane, select point 1 on production pane, ...)

- Points are selected by using *right-click* on the mouse
