### ISSUE TITLE
PNGWriter error even when following naming convention

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#133]
"Dr.Ho_PetersReduction_Carole_2017-10-26__Upper denture no Vertical 2_Result.stl" when selected as the source WILL give the PNGWriter error even though it follows the naming convention.

"Dr.Ho_PetersReduction_Carole_2017-10-26__Upper.stl" does not give the error when selected as source

Any thoughts @danaack

**Comment by danaack** [comment]
I tested this with "Dr.Ho_PetersReduction_Carole_2017-10-26__Upper denture no Vertical 2_Result.stl" as the source but did not receive any error

- Generated filename in Qt is "Report_2018-3-26_Dr.Ho_CarolePetersReduction_denturenoVertical2_Result"

- "Report_2018-3-26_Dr.Ho_CarolePetersReduction_denturenoVertical2_Result_1.png" and "Report_2018-3-26_Dr.Ho_CarolePetersReduction_denturenoVertical2_Result_1.html" are created successfully

My only hunch was that when I am concatenating the filenames I switch the screenshot filename from a string to a char[100] for easier appending, which I thought could be creating an error if we were exceeding that 100 character limit, but that filename is around 77 I think (I did count I just forget)

**Comment by danaack** [comment]
Fixed: #136
