### ISSUE TITLE
Video production

### ISSUE THREAD

**Issue by zifangah** [kseaman/Capstone3DModelling#134]
- screen-grab video filming by Saturday tentatively
- video editting by Monday tentatively
- improvements by Wednesday

**Comment by danaack** [comment]
Video to include: 
    1)    Fill out UI
    2)    3-point selection
            ⁃    Undo/redo a point during selection
    3)    Click enter
    4)    Rotate aligned models and heat map
    5)    Take additional screenshot
    6)    Quit program and open report

**Comment by danaack** [comment]
Wait for #125 , #124 , #123 , #56 to be closed (final visual features)

**Comment by zifangah** [comment]
@kseaman could you check on pull request 138 so that we can move on with final visual features?

**Comment by zifangah** [comment]
https://www.youtube.com/watch?v=UpQpP4Z5YUA
