### ISSUE TITLE
Write Test Case Report

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#17]
Based on your requirements document, revise it using the feedback provided from the grading
Create a table with each row showing the requirements of your report, and the following additional columns:
For each requirement, indicate what kind of test was used to test it
For each requirement, indicate if the test was passed or failed
For each requirement, indicate which team member contributed to making it work (coding and testing efforts)
In your table, to make it more compact, just use simple abbreviations like a checkmark for pass and a cross for fail, team member initials rather than full names, number code for type of test rather than spelling the whole thing out. Directly above your table, include a legend to explain your abbreviations.
This report is to be printed and submitted.

**Comment by danaack** [comment]
Template complete - to be updated with which team members were involved in the development/testing of each feature.
