### ISSUE TITLE
Add / Edit Requirements Doc

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#2]
Formatting into proper requirements doc styles.
Adding requirements gathered in Sept. 20th meeting.
Needs more thought on error report specifications and formats

Once done we can all go over it and add to it

Ideally ship it off to Eamonn before the next meeting

**Comment by danaack** [comment]
We don't need to send it to Eamonn before next meeting, we will go through it with him at the next meeting in-person.

**Comment by emersonk** [comment]
Ok sweet that works good for me, I won't have time to work on it until monday either
