### ISSUE TITLE
Write tutorial for setting up development environment

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#3]
How to set up environment including IDE, VTK, and ITK.

I will do the Windows tutorial.
Dana has volunteered to do Mac.

**Comment by emersonk** [comment]
Dana can we collab so that we have consistent styles between the two docs? Perhaps a google doc with a nice template? @danaack

**Comment by danaack** [comment]
Sounds good! I expect I won't be working on it until Monday

**Comment by emersonk** [comment]
Same deal!!

**Comment by danaack** [comment]
Mac tutorial finished: https://docs.google.com/document/d/11K4pb6gFsrVHguc2aKEeeqCeMbV5nVhbxB06omwECjM/edit?usp=sharing

I will bring a hard copy to the meeting tomorrow.
Task can be closed once Windows tutorial is complete.
