### ISSUE TITLE
Selected Points Highlighted

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#48]
Selected points need to stay highlighted
Autodetection

**Comment by zifangah** [comment]
- selected points from the model only, no off-image selection
- selected point is highlighted
- the first three pick on renderer 1 stays highlighted
- selecting points on renderer 2 is allowed
- selected points stay highlighted on renderer 2
- selected points coordinates are stored into ref and prod coordinates, message written into output.txt on a mac 
- more specific requirement for auto detection is needed from the client

**Comment by zifangah** [comment]
integrated
