### ISSUE TITLE
Distance Calculation 

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#56]
Emerson - 
- Send Karn aligned and slightly less aligned file. 
- Get alignment closer with https://www.vtk.org/Wiki/VTK/Examples/Cxx/Filtering/IterativeClosestPointsTransform

Karn - Try testing this out with the pug files
https://www.vtk.org/Wiki/VTK/Examples/Cxx/SimpleOperations/DistanceBetweenPoints

**Comment by danaack** [comment]
Things discussed to display on report: 

- Average distance away a point is out by (in the measurements selected by user)

- What percentage of points are within the threshold, and if that is within the confidence level specified

- Bell curve of point distances?

**Comment by danaack** [comment]
Most features complete: #136 
TODO - bell curve of point distances (display with shortcut key)

**Comment by danaack** [comment]
Histogram implemented #144
