### ISSUE TITLE
Clipping of models in right pane

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#70]

**Comment by emersonk** [comment]
I suspect this can be fixed with https://www.vtk.org/doc/nightly/html/classvtkCamera.html#details and the SetClippingRange method, but I have not tried yet.

**Comment by zifangah** [comment]
From 5th March client meeting: 
- Matching (0) of the same models -> locks the screens to share the same camera view -> no clipping occurs -> no issue
- fitting (1) of upper and lower models -> separate camera views
