### ISSUE TITLE
Clear All Points & Interactivity Between Panes

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#82]
- Be able to freeze panes (done but will need to be updated with code)
- Toggle moving in unison or not with regards to above (Emerson)
- Alternate points selecting (Emerson)
- Colour modification.

**Comment by zifangah** [comment]
maybe this might help: https://stackoverflow.com/questions/28580353/convert-mouse-position

**Comment by zifangah** [comment]
alternate point selection works now on remove-previous-pick branch
