### ISSUE TITLE
Status bar + Cancel Button

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#84]

**Comment by danaack** [comment]
Progress included in #89:

- Text displaying iteration number and cancel "hot-key"

- Visual display of current alignment

Additional changes to be implemented:

- Adding a cancel "hot-key" during iteration process (pending #88 and discussion around key-press events during a loop - I'm not sure if it's possible)

**Comment by zifangah** [comment]
@danaack i think it should work with pressing "e" even during iteration process

**Comment by emersonk** [comment]
We're going to leave it at this, the cancel key currently doesn't work because of limitations with the Iterative Closest Points Algorithm. I'm going to close this.
