### ISSUE TITLE
Development environment set up

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#9]
We need everybody to get their development environment correctly set up to work with the new architecture.

Everybody needs:

Qt 5.9
VTK 8.0.1
Github repo properly set up
Project building and compiling etc

Once you have it set up, please comment done and we will close this issue

**Comment by danaack** [comment]
Done

**Comment by emersonk** [comment]
I think we're as ready as we'll ever be, so I am closing this issue
